# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\content\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 128)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(530, 20, 75, 24))
        self.openButton.setObjectName("openButton")
        self.pathText = QtWidgets.QLineEdit(self.centralwidget)
        self.pathText.setGeometry(QtCore.QRect(20, 20, 501, 22))
        self.pathText.setObjectName("pathText")
        self.vehiclesCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.vehiclesCheck.setGeometry(QtCore.QRect(20, 60, 71, 20))
        self.vehiclesCheck.setChecked(True)
        self.vehiclesCheck.setObjectName("vehiclesCheck")
        self.pedestrianCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.pedestrianCheck.setGeometry(QtCore.QRect(110, 60, 91, 20))
        self.pedestrianCheck.setChecked(True)
        self.pedestrianCheck.setObjectName("pedestrianCheck")
        self.queuesCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.queuesCheck.setGeometry(QtCore.QRect(210, 60, 71, 20))
        self.queuesCheck.setChecked(True)
        self.queuesCheck.setObjectName("queuesCheck")
        self.boardingCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.boardingCheck.setGeometry(QtCore.QRect(300, 60, 81, 20))
        self.boardingCheck.setChecked(True)
        self.boardingCheck.setObjectName("boardingCheck")
        self.cycleCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.cycleCheck.setGeometry(QtCore.QRect(390, 60, 131, 20))
        self.cycleCheck.setChecked(True)
        self.cycleCheck.setObjectName("cycleCheck")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(530, 50, 75, 31))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 581, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel2PDF"))
        self.openButton.setText(_translate("MainWindow", "Open File"))
        self.pathText.setText(_translate("MainWindow", "Open subarea folder"))
        self.vehiclesCheck.setText(_translate("MainWindow", "Vehicles"))
        self.pedestrianCheck.setText(_translate("MainWindow", "Pedestrian"))
        self.queuesCheck.setText(_translate("MainWindow", "Queues"))
        self.boardingCheck.setText(_translate("MainWindow", "Boarding"))
        self.cycleCheck.setText(_translate("MainWindow", "Cycle and phases"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "STATE:"))